export const extraSlotDetails = [
  { id: 1, location: "Main Hall", instructor: "Emily Johnson" },
  { id: 2, location: "Room B202", instructor: "Michael Chen" },
  { id: 3, location: "Room A101", instructor: "Alex Rodriguez" },
  { id: 4, location: "Room C303", instructor: "Sarah Thompson" },
  { id: 5, location: "Auditorium", instructor: "Daniel Kim" },
  { id: 6, location: "Lab 1", instructor: "Olivia Brown" },
  { id: 7, location: "Room D404", instructor: "James Lee" },
  { id: 8, location: "Room A102", instructor: "Isabella Martinez" },
  { id: 9, location: "Room B201", instructor: "William Davis" },
  { id: 10, location: "Seminar Hall", instructor: "Mia Wilson" },
  { id: 11, location: "Room E101", instructor: "David Garcia" },
  { id: 12, location: "Room C201", instructor: "Emma Clark" },
  { id: 13, location: "Lab 2", instructor: "Benjamin Lewis" },
  { id: 14, location: "Room A103", instructor: "Sophia Walker" },
  { id: 15, location: "Conference Room", instructor: "Logan Hall" },
  { id: 16, location: "Room D405", instructor: "Grace Young" },
  { id: 17, location: "Room B204", instructor: "Lucas King" },
  { id: 18, location: "Training Room", instructor: "Chloe Allen" },
  { id: 19, location: "Room F101", instructor: "Henry Wright" },
  { id: 20, location: "Lecture Hall 2", instructor: "Amelia Scott" },
  { id: 21, location: "Room G301", instructor: "Liam Green" },
  { id: 22, location: "Room H202", instructor: "Ella Adams" },
  { id: 23, location: "Room A104", instructor: "Jacob Nelson" },
  { id: 24, location: "Lab 3", instructor: "Avery Baker" },
  { id: 25, location: "Room C204", instructor: "Matthew Hill" },
  { id: 26, location: "Lecture Room 1", instructor: "Scarlett Ramirez" },
  { id: 27, location: "Room D101", instructor: "Owen Campbell" },
  { id: 28, location: "Room A105", instructor: "Lily Mitchell" },
  { id: 29, location: "Seminar Hall", instructor: "Jack Carter" },
  { id: 30, location: "Room B205", instructor: "Natalie Perez" },
  { id: 31, location: "Room C305", instructor: "Gabriel Rivera" },
  { id: 32, location: "Room D303", instructor: "Zoe Cooper" },
  { id: 33, location: "Room E303", instructor: "Wyatt Bailey" },
  { id: 34, location: "Room F202", instructor: "Layla Reed" },
  { id: 35, location: "Main Hall", instructor: "Nathan Bell" },
  { id: 36, location: "Room A106", instructor: "Riley Murphy" },
  { id: 37, location: "Room B206", instructor: "Eli Price" },
  { id: 38, location: "Room C306", instructor: "Aria Barnes" },
  { id: 39, location: "Lecture Hall 3", instructor: "Levi Jenkins" },
  { id: 40, location: "Room D304", instructor: "Hazel Simmons" },
  { id: 41, location: "Room E202", instructor: "Sebastian Flores" },
  { id: 42, location: "Training Room", instructor: "Violet Butler" },
  { id: 43, location: "Room A107", instructor: "Caleb Gonzales" },
  { id: 44, location: "Room B207", instructor: "Luna Hayes" },
  { id: 45, location: "Room C307", instructor: "Isaac Patterson" },
  { id: 46, location: "Lab 4", instructor: "Aurora James" },
  { id: 47, location: "Room D305", instructor: "Julian Brooks" },
  { id: 48, location: "Room E203", instructor: "Penelope Kelly" },
  { id: 49, location: "Room F203", instructor: "Anthony Sanders" },
  { id: 50, location: "Room G302", instructor: "Madelyn Morris" },
];
